import React, { useEffect, useState } from "react";
import { Landmark, Pencil, Plus, Save, Trash2, X } from "lucide-react";
import { toast } from "react-hot-toast";
import { addFinancePartner, deleteFinancePartner, getFinancePartners, updateFinancePartner } from "../../lib/firestore";
import { FinancePartner, FinancePartnerType } from "../../types";

const emptyForm = { name: "", type: "Bank" as FinancePartnerType, interestRateMin: 8, interestRateMax: 10, tenureYears: "Up to 20 years", eligibility: "", notes: "", website: "", published: false };

export const FinanceAdminPanel: React.FC = () => {
  const [partners, setPartners] = useState<FinancePartner[]>([]);
  const [form, setForm] = useState(emptyForm);
  const [editingId, setEditingId] = useState<string | null>(null);
  const [formOpen, setFormOpen] = useState(false);

  const load = async () => setPartners(await getFinancePartners(true));
  useEffect(() => { load().catch(() => toast.error("Finance directory could not be loaded.")); }, []);
  const update = <K extends keyof typeof emptyForm>(key: K, value: (typeof emptyForm)[K]) => setForm((current) => ({ ...current, [key]: value }));
  const edit = (partner: FinancePartner) => { setEditingId(partner.id); setForm({ name: partner.name, type: partner.type, interestRateMin: partner.interestRateMin, interestRateMax: partner.interestRateMax, tenureYears: partner.tenureYears, eligibility: partner.eligibility, notes: partner.notes || "", website: partner.website || "", published: partner.published }); setFormOpen(true); };
  const reset = () => { setEditingId(null); setForm(emptyForm); setFormOpen(false); };
  const save = async (event: React.FormEvent) => { event.preventDefault(); if (!form.name.trim() || !form.eligibility.trim()) { toast.error("Lender name and eligibility notes are required."); return; } try { if (editingId) await updateFinancePartner(editingId, form); else await addFinancePartner(form); toast.success(editingId ? "Finance partner updated." : "Finance partner added."); reset(); await load(); } catch { toast.error("Could not save finance partner."); } };
  const remove = async (id: string) => { if (!window.confirm("Remove this finance partner?")) return; try { await deleteFinancePartner(id); toast.success("Finance partner removed."); await load(); } catch { toast.error("Could not remove finance partner."); } };

  return <div className="space-y-6" id="finance-admin-panel"><div className="flex flex-wrap items-center justify-between gap-4 border-b border-slate-200 pb-4"><div><h2 className="font-serif text-2xl font-bold text-[#6B1A2A]">Bank & NBFC Finance Repository</h2><p className="text-xs text-slate-500">Add only verified partner details. Published entries appear on the public finance comparison table.</p></div><button onClick={() => { setForm(emptyForm); setEditingId(null); setFormOpen(true); }} className="inline-flex items-center gap-2 rounded-xl bg-[#C45C1A] px-4 py-2.5 text-xs font-bold uppercase text-white"><Plus className="h-4 w-4" />Add Lender</button></div>
    {formOpen && <form onSubmit={save} className="rounded-2xl border border-[#C9A84C]/30 bg-white p-5 shadow-sm"><div className="mb-4 flex items-center justify-between"><h3 className="font-serif text-lg font-bold text-[#1A1A2E]">{editingId ? "Edit Finance Partner" : "New Finance Partner"}</h3><button type="button" onClick={reset} className="text-slate-400"><X className="h-5 w-5" /></button></div><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Field label="Lender name" value={form.name} onChange={(v) => update("name", v)} /><label className="text-xs font-bold text-slate-600">Type<select value={form.type} onChange={(e) => update("type", e.target.value as FinancePartnerType)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900"><option>Bank</option><option>NBFC</option></select></label><Field label="Min rate %" type="number" value={String(form.interestRateMin)} onChange={(v) => update("interestRateMin", Number(v))} /><Field label="Max rate %" type="number" value={String(form.interestRateMax)} onChange={(v) => update("interestRateMax", Number(v))} /><Field label="Tenure options" value={form.tenureYears} onChange={(v) => update("tenureYears", v)} /><Field label="Website (optional)" value={form.website} onChange={(v) => update("website", v)} /><label className="text-xs font-bold text-slate-600 sm:col-span-2">Eligibility notes<textarea required value={form.eligibility} onChange={(e) => update("eligibility", e.target.value)} rows={2} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900" /></label><label className="text-xs font-bold text-slate-600 sm:col-span-2">Additional notes<textarea value={form.notes} onChange={(e) => update("notes", e.target.value)} rows={2} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900" /></label></div><label className="mt-4 flex items-center gap-2 text-xs font-bold text-slate-700"><input type="checkbox" checked={form.published} onChange={(e) => update("published", e.target.checked)} />Publish on public finance comparison page</label><button className="mt-5 inline-flex items-center gap-2 rounded-xl bg-[#0F172A] px-4 py-2.5 text-xs font-bold uppercase text-white"><Save className="h-4 w-4" />Save Partner</button></form>}
    {partners.length === 0 ? <div className="rounded-2xl border border-dashed border-slate-200 bg-white p-10 text-center text-sm text-slate-500"><Landmark className="mx-auto mb-2 h-7 w-7 text-[#C45C1A]" />No finance partners have been added yet.</div> : <div className="overflow-x-auto rounded-2xl border border-slate-200 bg-white"><table className="w-full min-w-[760px] text-left text-sm"><thead className="bg-slate-50 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="px-4 py-3">Lender</th><th>Type</th><th>Rate</th><th>Tenure</th><th>Status</th><th className="px-4">Actions</th></tr></thead><tbody>{partners.map((partner) => <tr key={partner.id} className="border-t border-slate-100"><td className="px-4 py-4 font-bold text-[#1A1A2E]">{partner.name}</td><td>{partner.type}</td><td>{partner.interestRateMin}% - {partner.interestRateMax}%</td><td>{partner.tenureYears}</td><td><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${partner.published ? "bg-emerald-100 text-emerald-700" : "bg-slate-100 text-slate-500"}`}>{partner.published ? "Published" : "Draft"}</span></td><td className="px-4"><button onClick={() => edit(partner)} className="mr-3 text-[#C45C1A]" aria-label={`Edit ${partner.name}`}><Pencil className="h-4 w-4" /></button><button onClick={() => remove(partner.id)} className="text-red-600" aria-label={`Delete ${partner.name}`}><Trash2 className="h-4 w-4" /></button></td></tr>)}</tbody></table></div>}
  </div>;
};

const Field = ({ label, value, onChange, type = "text" }: { label: string; value: string; onChange: (value: string) => void; type?: string }) => <label className="text-xs font-bold text-slate-600">{label}<input type={type} value={value} onChange={(e) => onChange(e.target.value)} className="mt-1 w-full rounded-xl border border-slate-200 px-3 py-2.5 text-sm text-slate-900" /></label>;
